from aiogram.dispatcher.filters.state import StatesGroup, State

class PersonalDataRu(StatesGroup):
    writeForms = State()
    writePost = State()
    modelName = State()
    memoryRam = State()
    newSecond = State()
    phoneWorkingTime = State()
    statePhone = State()
    phoneColor = State()
    phoneProblem = State()
    boxPass = State()
    accessories = State()
    exchange_callback = State()
    exchange = State()
    addInfo = State()
    price = State()
    phoneNumber = State()
    photoVideo = State()
    Confirm = State()
    ConfirmAdmin = State()
    finished = State()
    new_ads = State()
    deletePost = State()